# This is a generated file. Not intended for manual editing.
services:
  rpweave.server.api:
    build:
      context: "/home/vasil/Projects/rp_weave/src/RpWeave.Server"
      dockerfile: "RpWeave.Server.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/RpWeave.Server.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "rpweave.server.api:dev"
    ports: []
    volumes:
    - "/home/vasil/Projects/rp_weave/src/RpWeave.Server/RpWeave.Server.Api:/app:rw"
    - "/home/vasil/Projects/rp_weave/src/RpWeave.Server:/src:rw"
    - "/home/vasil/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
