# This is a generated file. Not intended for manual editing.
services:
  rpweave.server.api:
    build:
      context: "/home/vasil/Projects/rp_weave/src/RpWeave.Server"
      dockerfile: "RpWeave.Server.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "rpweave.server.api:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/vasil/Projects/rp_weave/src/RpWeave.Server/RpWeave.Server.Api:/app:rw"
    - "/home/vasil/Projects/rp_weave/src/RpWeave.Server:/src:rw"
    - "/home/vasil/.nuget/packages:/root/.nuget/packages"
    - "/home/vasil/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/vasil/Programs/Rider/JetBrains Rider-2024.3.7/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/vasil/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_11_19_12_03_37:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
